HIP 1007 Enhance Mirror Node Contract Log REST API with transaction hash
hashgraph/hedera-improvement-proposal pull request #1008
Opened 2024-07-12 17:33 UTC by georgi-l95

**Description**:
This PR describes the enhancment of the mirror node contract log rest api with transaction hash query parameter

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-07-12 18:08 UTC, steven-sheehy requested changes

2024-07-12 18:08 UTC, steven-sheehy commented on HIP/hip-1008.md
> +Note: if`limit` is not specified in the request, response will be limited to 25 by default
```suggestion
Note: If `limit` is not specified in the request, the response will be limited to 25 by default.
```

2024-07-12 18:08 UTC, steven-sheehy commented on HIP/hip-1008.md
> +**`/api/v1/contracts/results/logs?transaction.hash=0xda1aee3c386763b2cb2e830765053e346d11deff1c343a5fefe84910f9dfe63b`**
```suggestion

`/api/v1/contracts/results/logs?transaction.hash=0xda1aee3c386763b2cb2e830765053e346d11deff1c343a5fefe84910f9dfe63b`
```

2024-07-12 18:08 UTC, steven-sheehy commented on HIP/hip-1008.md
> +A new transaction.hash parameter will be added to search for contracts logs by their hash. This transaction hash query parameter should be in hex format with optional leading `0x` prefix and will sup
```suggestion
A new `transaction.hash` parameter will be added to search for contracts logs by their hash. This transaction hash query parameter should be in hex format with optional leading `0x` prefix and will support both 32 byte Ethereum and 48 byte Hedera transaction hashes.
```

2024-07-12 18:12 UTC, steven-sheehy submitted a review, later dismissed
LGTM

2024-07-13 18:55 UTC, xin-hedera approved these changes
LGTM

2024-07-15 11:42 UTC, Nana-EC approved these changes

2024-07-20 01:24 UTC, Nana-EC submitted a review, later dismissed

2024-07-24 23:49 UTC, Neurone commented
Hi guys, how is this different from using the [`/api/v1/contracts/results/{transactionIdOrHash}`](https://mainnet.mirrornode.hedera.com/api/v1/docs/#/contracts/getContractResultByTransactionIdOrHash) endpoint?

For example[, this is just a random mainnet transaction](https://mainnet.mirrornode.hedera.com/api/v1/contracts/results/0xcc7bfea2d35e4bcf27bfe60d19433efa8e03f3d6fbafebe0e21c0f24bcee3d0f), and I can get the logs by querying the mirror node with the 32 byte Ethereum format, and I get all the logs:

```zsh
⮞ curl --silent https://mainnet.mirrornode.hedera.com/api/v1/contracts/results/0xcc7bfea2d35e4bcf27bfe60d19433efa8e03f3d6fbafebe0e21c0f24bcee3d0f | jq
{
  "address": "0x00000000000000000000000000000000003c437a",
  "amount": 2500000000000,
  "bloom": "0x00000080000000102001000000000000000000000000020100000000000020000000000000000000800000000000000000000000010022000000004040020040010040000008200800000000000000000000008000800001000000000000000000000000020000000000000000200800000000000000000000200040000880000000000000000000000000008000000000000000000000000000200000000000000080000004000000000000000000000000000000000000000000000000000000080001000000000000000000000000000000000000000000000000000020000000000000000004000000000800000000000000000080100000000000800000",
  "call_result": "0x0000000000000000000000000000000000000000000000000000000062a349f6",
  "contract_id": "0.0.3949434",
  "created_contract_ids": [],
  "error_message": null,
  "from": "0x000000000000000000000000000000000056dc0c",
  "function_parameters": "0x414bf3890000000000000000000000000000000000000000000000000000000000163b5a000000000000000000000000000000000000000000000000000000000006f89a00000000000000000000000000000000000000000000000000000000000005dc000000000000000000000000756dab6280de64f2c58a2c693a1528fcaf23ec5a0000000000000000000000000000000000000000000000000000000066a18f8900000000000000000000000000000000000000000000000000000246139ca80000000000000000000000000000000000000000000000000000000000629b8d9c0000000000000000000000000000000000000000000000000000000000000000",
  "gas_consumed": 209996,
  "gas_limit": 2000000,
  "gas_used": 1600000,
  "timestamp": "1721863475.979812003",
  "to": "0x00000000000000000000000000000000003c437a",
  "hash": "0xcc7bfea2d35e4bcf27bfe60d19433efa8e03f3d6fbafebe0e21c0f24bcee3d0f",
  "block_hash": "0x702fa733df1414be14a5fa96fa6e487b363fb6e2dfc62fd3b457aa9365e58818673d13d54760641e90e9a11c1c691d1c",
  "block_number": 66915917,
  "logs": [
    {
      "address": "0xc5b707348da504e9be1bd4e21525459830e7b11d",
      "bloom": "0x00000080000000000000000000000000000000000000020000000000000020000000000000000000000000000000000000000000010000000000000000000040000040000000000000000000000000000000008000800000000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000008000000000000000000000000000200000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000004000000000800000000000000000000000000000000800000",
      "contract_id": "0.0.3964804",
      "data": "0x0000000000000000000000000000000000000000000000000000000062a349f6",
      "index": 0,
      "topics": [
        "0x5f2147fb558c977441fbdfebcf8cd5776606adc8da5ff95566fc2a4137e54d13",
        "0x000000000000000000000000c5b707348da504e9be1bd4e21525459830e7b11d",
        "0x000000000000000000000000756dab6280de64f2c58a2c693a1528fcaf23ec5a",
        "0x000000000000000000000000000000000000000000000000000000000006f89a"
      ]
    },
    {
      "address": "0x0000000000000000000000000000000000163b59",
      "bloom": "0x00000000000000102001000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000004000020000000000000000000000000000000000000000000000000001000000000000000000000000020000000000000000000800000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000020000000000000000000000000000000000000000000000000100000000000000000",
      "contract_id": "0.0.1456985",
      "data": "0x00000000000000000000000000000000000000000000000000000246139ca800",
      "index": 1,
      "topics": [
        "0x831ac82b07fb396dafef0077cea6e002235d88e63f35cbd5df2c065107f1e74a",
        "0x0000000000000000000000000000000000000000000000000000000000000000",
        "0x00000000000000000000000000000000000000000000000000000000003c437a"
      ]
    },
    {
      "address": "0x0000000000000000000000000000000000163b59",
      "bloom": "0x00000000000000102001000000000000000000000000000000000000000000000000000000000000800000000000000000000000000000000000004000020000010000000000000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000040000000000000000000000000000000000000000000000000000000000000000000000000000080000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000080100000000000000000",
      "contract_id": "0.0.1456985",
      "data": "0x00000000000000000000000000000000000000000000000000000246139ca800",
      "index": 2,
      "topics": [
        "0x831ac82b07fb396dafef0077cea6e002235d88e63f35cbd5df2c065107f1e74a",
        "0x0000000000000000000000000000000000000000000000000000000000163b59",
        "0x00000000000000000000000000000000000000000000000000000000003c437a"
      ]
    },
    {
      "address": "0x0000000000000000000000000000000000163b59",
      "bloom": "0x00000000000000102000000000000000000000000000000000000000000000000000000000000000800000000000000000000000000002000000004040020000000000000008000000000000000000000000000000000001000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
      "contract_id": "0.0.1456985",
      "data": "0x00000000000000000000000000000000000000000000000000000246139ca800",
      "index": 3,
      "topics": [
        "0x5548c837ab068cf56a2c2479df0882a4922fd203edb7517321831d95078c5f62",
        "0x00000000000000000000000000000000000000000000000000000000003c437a",
        "0x00000000000000000000000000000000000000000000000000000000003c437a"
      ]
    },
    {
      "address": "0x00000000000000000000000000000000003c437a",
      "bloom": "0x00000000000000002000000000000000000000000000000100000000000000000000000000000000800000000000000000000000000000000000000000020040000040000000200000000000000000000000008000000000000000000000000000000000000000000000000000200000000000000000000000200000000000000000000000000000000000000000000000000000000000000000200000000000000000000004000000000000000000000000000000000000000000000000000000080001000000000000000000000000000000000000000000000000000000000000000000000004000000000000000000000000000000000000000000000000",
      "contract_id": "0.0.3949434",
      "data": "0x00000000000000000000000000000000000000000000000000000246139ca800",
      "index": 4,
      "topics": [
        "0x5f2147fb558c977441fbdfebcf8cd5776606adc8da5ff95566fc2a4137e54d13",
        "0x00000000000000000000000000000000000000000000000000000000003c437a",
        "0x000000000000000000000000c5b707348da504e9be1bd4e21525459830e7b11d",
        "0x0000000000000000000000000000000000000000000000000000000000163b5a"
      ]
    },
    {
      "address": "0xc5b707348da504e9be1bd4e21525459830e7b11d",
      "bloom": "0x00000080000000002000000000000000000000000000020000000000000020000000000000000000800000000000000000000000000020000000000000020000000000000000000800000000000000000000000000800000000000000000000000000000000000000000000000000000000000000000000000000000000800000 [...]

2024-07-25 18:51 UTC, georgi-l95 commented
> Hi guys, how is this different from using the [`/api/v1/contracts/results/{transactionIdOrHash}`](https://mainnet.mirrornode.hedera.com/api/v1/docs/#/contracts/getContractResultByTransactionIdOrHash) endpoint?
> 
> For example, [this is just a random mainnet transaction](https://mainnet.mirrornode.hedera.com/api/v1/contracts/results/0xcc7bfea2d35e4bcf27bfe60d19433efa8e03f3d6fbafebe0e21c0f24bcee3d0f), and I can get the logs by querying the mirror node with the 32 byte Ethereum format, and I get all the logs:
> 
> ```shell
> ⮞ curl --silent https://mainnet.mirrornode.hedera.com/api/v1/contracts/results/0xcc7bfea2d35e4bcf27bfe60d19433efa8e03f3d6fbafebe0e21c0f24bcee3d0f | jq
> ```

Hey @Neurone thanks for pointing this out. Difference here is that this endpoint is querying from `contract_results` table in the database, where contract/logs is querying from `contract_logs` table. Not all transactions are logged in the `contract_results` table, for example HTS trasnfer and approve. Their events are only added in the latter database table.

2024-07-25 23:26 UTC, mgarbs approved these changes

2024-07-25 23:27 UTC, merged

2024-07-26 14:37 UTC, Neurone commented
Hi Georgi, thanks for the clarification.

I think we should take advantage of the change to match the log values in the `/api/v1/contracts/results/{transactionIdOrHash}` endpoint to the expected results (all logs relative to that transaction).

The DB query should be able to read this information and associate it with the result.

We can also add a `/api/v1/contracts/results/{transactionIdOrHash}/logs` endpoint in case the developers just want to get the logs, and in that case it would be a read from the `contract_logs` table only. This is exactly the behaviour we would have got with the new `/api/v1/contracts/results/logs?transaction.hash={value}` syntax, but now with a more coherent syntax.

This way we both cover the need to have the full log list and address the misunderstanding about data for those projects that use the logs value returned by the `/api/v1/contracts/results/{transactionIdOrHash}`.

If the `contract_logs' table contains all the logs, we can also take the opportunity to free up some space in the `contract_results' table.

@steven-sheehy @xin-hedera What do you think?