Verious formatting updates
hashgraph/hedera-improvement-proposal pull request #134
Opened 2021-09-08 16:30 UTC by sergmetelin

This PR includes various formatting updates

2021-09-09 11:24 UTC, gregscullard requested changes
`In addition, I can also decrease the number of associations, and that call will succeed if the new (decreased) number that I have specified is greater than or equal to the current number of automatic associations that I have already used.`

I can think of a corner case where I’ve allowed 100 associations, used them (associationCount=100) and then manually associate with 2 more. If I want to decrease the number of automatic association, how will dissociating from a token reduce the association count ? Will it only do so when I have removed two tokens (which may have been associated automatically) and start dissociating other tokens (could be the last 2 I associated with). Or do we keep track of which tokens were automatically associated and only dissociating from these decrements the counter ?

2021-09-09 11:26 UTC, gregscullard commented
The intro (and some of the text) refers to wallet or wallets where I think account would be preferable (happy to proceed without change)

2021-09-14 13:40 UTC, sergmetelin commented
> `In addition, I can also decrease the number of associations, and that call will succeed if the new (decreased) number that I have specified is greater than or equal to the current number of automatic associations that I have already used.`
> 
> I can think of a corner case where I’ve allowed 100 associations, used them (associationCount=100) and then manually associate with 2 more. If I want to decrease the number of automatic association, how will dissociating from a token reduce the association count ? Will it only do so when I have removed two tokens (which may have been associated automatically) and start dissociating other tokens (could be the last 2 I associated with). Or do we keep track of which tokens were automatically associated and only dissociating from these decrements the counter ?

My understanding is that the number of auto-associations will be tracked independently of the number of manual associations.

2021-09-14 13:44 UTC, gregscullard approved these changes

2021-09-14 13:45 UTC, gregscullard approved these changes

2021-09-14 13:45 UTC, merged