Add Message Sender's Account Id to Mirror Node API Response
hashgraph/hedera-improvement-proposal pull request #171
Opened 2021-10-18 16:32 UTC by scalemaildev

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2021-11-04 17:21 UTC, sergmetelin requested changes

2021-11-04 17:21 UTC, sergmetelin commented on HIP/hip-0000-mirror-node-account-id.md
> +- hip: <HIP number (this is determined by the HIP editor)>
Do you mind aligning it with the new HIP-1 and the new https://github.com/hashgraph/hedera-improvement-proposal/blob/master/hip-0000-template.md template?

The header should be reformatted to align with the table structure (remove `-` at each line in the header and wrap the header with `---` on top and bottom.

Please also make note that the review process has changed as well.

2021-11-04 17:21 UTC, sergmetelin commented on HIP/hip-0000-mirror-node-account-id.md
> +- author: scalemaildev
Please adjust to the `author` field formatting referenced in HIP-1

2021-11-04 17:21 UTC, sergmetelin commented on HIP/hip-0000-mirror-node-account-id.md
> +- status: Draft
Once the HIP is ready for review by the editors, please change the status to `Review`

2021-11-04 17:21 UTC, sergmetelin commented on HIP/hip-0000-mirror-node-account-id.md
> +- discussions-to: <a URL pointing to the official discussion thread>
Please create a new discussion thread in the `Discussions` tab and link to it here

2021-11-04 17:21 UTC, sergmetelin commented on HIP/hip-0000-mirror-node-account-id.md
> +- updated: <comma separated list of dates>
Please remove unused fields

2021-11-04 17:21 UTC, sergmetelin commented on HIP/hip-0000-mirror-node-account-id.md
> +The technical specification should describe the syntax and semantics of any new features. The specification should be detailed enough to allow competing, interoperable implementations for at least th
Please fill out these sections to your best knowledge or leave them empty. Please note that the HIP can't be considered complete without Specification.

2021-11-04 19:32 UTC, scalemaildev commented
I made the requested changes to the markdown file. Logs show this error:

```
2:28:58 PM: ────────────────────────────────────────────────────────────────
2:28:58 PM:   1. Build command from Netlify app                             
2:28:58 PM: ────────────────────────────────────────────────────────────────
2:28:58 PM: ​
2:28:58 PM: $ bundle exec jekyll build
2:28:58 PM: Could not locate Gemfile or .bundle/ directory
2:28:58 PM: ​
2:28:58 PM: ────────────────────────────────────────────────────────────────
2:28:58 PM:   "build.command" failed                                        
2:28:58 PM: ────────────────────────────────────────────────────────────────
2:28:58 PM: ​
2:28:58 PM:   Error message
2:28:58 PM:   Command failed with exit code 10: bundle exec jekyll build
2:28:58 PM: ​
2:28:58 PM:   Error location
2:28:58 PM:   In Build command from Netlify app:
2:28:58 PM:   bundle exec jekyll build
```

2021-11-08 20:24 UTC, sergmetelin approved these changes
LGTM

2021-11-08 20:24 UTC, merged