Update HIP-21 with latest protobuf
hashgraph/hedera-improvement-proposal pull request #340
Opened 2022-01-21 22:30 UTC by steven-sheehy

**Description**:
Updates HIP-21 with the protobuf currently implemented on the mirror node.

**Related issue(s)**:

**Notes for reviewer**:

**Checklist**

- [x] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-01-24 23:25 UTC, Nana-EC requested changes
LG, a minor nit

2022-01-24 23:25 UTC, Nana-EC commented on HIP/hip-21.md
> +The gRPC API will use server streaming technology to deliver all of the `NodeAddress` entries contained within the latest address book. The stream will automatically complete when all entries are del
```suggestion
The gRPC API will use server streaming technology to deliver all of the `NodeAddress` entries contained within the latest address book. The stream will automatically complete when all entries are delivered, avoiding the complexity of client side paging.
```

2022-01-25 04:28 UTC, steven-sheehy commented on HIP/hip-21.md
> +The gRPC API will use server streaming technology to deliver all of the `NodeAddress` entries contained within the latest address book. The stream will automatically complete when all entries are del
Fixed

2022-02-01 14:44 UTC, sergmetelin approved these changes

2022-02-01 14:44 UTC, merged