Add files extension information in HIP-435 Record Stream 6
hashgraph/hedera-improvement-proposal pull request #517
Opened 2022-07-01 06:07 UTC by stoqnkpL

Signed-off-by: Stoyan Panayotov <stoyan.panayotov@limechain.tech>

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-07-01 06:09 UTC, stoqnkpL commented
@steven-sheehy I'm not allowed to add PR reviewers in this repo but I think you have context and can approve

2022-07-01 13:33 UTC, steven-sheehy requested changes

2022-07-01 15:39 UTC, stoqnkpL commented on HIP/hip-435.md
> +Record File: 2022-10-19T21_35_39.000000000Z.rcd
I haven't seen the compressed files and I thought they would have only the `.gz` extension and would uncompress to `.rcd`. Fixed.

2022-07-04 22:02 UTC, steven-sheehy approved these changes

2022-07-05 18:36 UTC, merged