zero token operations
hashgraph/hedera-improvement-proposal pull request #564
Opened 2022-09-02 00:10 UTC by littletarzan

Signed-off-by: littletarzan <mdelore.ufl@gmail.com>

**Description**:

**Related issue(s)**:

Fixes #

**Notes for reviewer**:

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2022-09-06 18:42 UTC, mgarbs requested changes
I left a few comments. Also, a couple of things:

- This hip should be inside the `/HIP` folder of your fork instead of the root directory.
- This hip is failing the validation check https://github.com/hashgraph/hedera-improvement-proposal/runs/8209056776?check_suite_focus=true You'll need to tweak the headers a bit in order for it to pass.

2022-09-06 18:42 UTC, mgarbs commented on hip-0000-zero-token-operations.md
> +To reduce code, if statement checks, etc inside smart contracts and make DeFi contracts easier to use. To reduce bugs in DeFi applications involving math and rounding.
Perhaps we can flesh this out a bit?
From [hip-1](https://hips.hedera.com/hip/hip-1):
The motivation should clearly explain why the existing specification is inadequate to address the problem that the HIP solves.

2022-09-06 18:42 UTC, mgarbs commented on hip-0000-zero-token-operations.md
> +The rationale should provide evidence of consensus within the community and discuss important objections or concerns raised during the discussion.
There is some default text here from the template hip that we should remove. Also, the rationale is your chance to really explain the reasoning behind why the hip is useful. From hip-1:

_The rationale fleshes out the specification by describing why particular design decisions were made. It should describe alternate designs that were considered and related work, e.g. how the feature is supported in other languages._

_The rationale should provide evidence of consensus within the community and discuss important objections or concerns raised during the discussion._

2022-09-06 18:42 UTC, mgarbs commented on hip-0000-zero-token-operations.md
> +hip: <HIP number (this is determined by the HIP editor)>
```suggestion
hip: 0000
```

2022-09-06 18:44 UTC, mgarbs commented on hip-0000-zero-token-operations.md
> +author: littletarzan, vae.vecturne
should be:
author: Firstname LastName <email>, Firstname1 LastName1 <email1>

2022-09-06 18:45 UTC, mgarbs commented on hip-0000-zero-token-operations.md
> +created: Sept 1, 2022
```suggestion
created: 2022-09-01
```

2022-09-06 18:45 UTC, mgarbs commented on hip-0000-zero-token-operations.md
> +superseded-by: <HIP number(s)>
```suggestion
```

2022-09-06 18:46 UTC, mgarbs commented on hip-0000-zero-token-operations.md
> +needs-council-approval: No
```suggestion
needs-council-approval: Yes
```

2022-09-07 00:34 UTC, littletarzan commented
@mgarbs thank you, I made the requested changes

2022-09-07 12:45 UTC, mgarbs requested changes

2022-09-07 12:45 UTC, mgarbs commented on HIP/hip-0000-zero-token-operations.md
> +The rationale should provide evidence of consensus within the community and discuss important objections or concerns raised during the discussion.
```suggestion
```

2022-09-07 12:45 UTC, mgarbs commented on HIP/hip-0000-zero-token-operations.md
> +To reduce code, if statement checks, etc inside smart contracts and make DeFi contracts easier to use. To reduce bugs in DeFi applications involving math and rounding.
```suggestion
Currently, whenever a zero value parameter passes through a mint, burn or transfer transaction, the network rejects it immediately. Frequently this happens with integer rounding calculations in smart contracts. To get around it, contract developers must check for a non-zero value to submit mint, burn or transfer transactions, which is inconsistent with most other networks. This hip will eliminate `if` statements checking for zero before mint, burn or transfer transactions in smart contracts making them easier to use and be in alignment with most other networks.
```

2022-09-07 12:45 UTC, mgarbs commented on HIP/hip-0000-zero-token-operations.md
> +
```suggestion
N/A
```

2022-09-07 12:45 UTC, mgarbs commented on HIP/hip-0000-zero-token-operations.md
> +
```suggestion
N/A
```

2022-09-07 12:45 UTC, mgarbs commented on HIP/hip-0000-zero-token-operations.md
> +
```suggestion
#### Example :

Example of a transfer transaction that should be allowed if a 0 amount is passed.
```js
function mint(uint amount) external {
        balanceOf[msg.sender] += amount;
        totalSupply += amount;
        emit Transfer(address(0), msg.sender, amount);
 }
 
```
```

2022-09-07 12:47 UTC, mgarbs commented on HIP/hip-0000-zero-token-operations.md
> +working-group:
```suggestion
```

2022-09-07 18:37 UTC, mgarbs commented on HIP/hip-0000-zero-token-operations.md
> +
```suggestion
```
```

2022-09-07 18:39 UTC, mgarbs commented on HIP/hip-0000-zero-token-operations.md
> +Example of a transfer transaction that should be allowed if a 0 amount is passed.
```suggestion
Example of a mint transaction that should be allowed if a 0 amount is passed.
```

2022-09-07 18:44 UTC, mgarbs commented on HIP/hip-0000-zero-token-operations.md
> +type: Standards track
```suggestion
type: Standards Track
```

2022-09-07 19:39 UTC, mgarbs submitted a review, later dismissed

2022-09-07 21:43 UTC, mgarbs approved these changes

2022-09-07 21:43 UTC, merged