Create nft allowance hip (#1)
hashgraph/hedera-improvement-proposal pull request #857
Opened 2024-01-16 18:01 UTC by mgoelswirlds

**Description**:

This HIP designs Nft Allowances APIs for mirror node.

**Notes for reviewer**:
This will remain a Draft until the approved by the council

**Checklist**

- [ ] Documented (Code comments, README, etc.)
- [ ] Tested (unit, integration, etc.)

2024-01-18 18:10 UTC, steven-sheehy requested changes

2024-01-18 18:10 UTC, steven-sheehy commented on HIP/hip-857.md
> +		"next": "/api/v1/accounts/0.0.1000/allowances/nfts?limit=3&order=asc&account.id=gte:9857&token.id=gt:0.0.1034"
limit=3 would have to be in the initial URL for this link to be accurate. Same for other example.

2024-01-18 18:10 UTC, steven-sheehy commented on HIP/hip-857.md
> +		"next": "/api/v1/accounts/0.0.1000/allowances/nfts?limit=3&order=asc&account.id=gte:9857&token.id=gt:0.0.1034"
We sort first by spender so we would exclude rows if gt:0.0.1034
```suggestion
		"next": "/api/v1/accounts/0.0.1000/allowances/nfts?limit=3&order=asc&account.id=gte:9857&token.id=gt:0.0.1032"
```

2024-01-18 18:10 UTC, steven-sheehy commented on HIP/hip-857.md
> +- `limit`: The maximum number of items to return.
```suggestion
- `limit`: The maximum number of items to return. Defaults to 25 with a maximum of 100 allowed.
```

2024-01-18 18:10 UTC, steven-sheehy commented on HIP/hip-857.md
> +- `order`: Order by `token.id` and `account.id`. Accepts `asc` or `desc` with a default of `asc`.
```suggestion
- `order`: Order by  `account.id` then `token.id`. Accepts `asc` or `desc` with a default of `asc`.
```

2024-01-18 18:10 UTC, steven-sheehy commented on HIP/hip-857.md
> +- `token.id`: Filter by the token ID. `ne` operator is not supported.
```suggestion
- `token.id`: Filter by the token ID. `ne` operator is not supported. Only one occurrence allowed.
```

2024-01-18 18:10 UTC, steven-sheehy commented on HIP/hip-857.md
> +- `account.id`: Filter by the spender account ID or owner account ID, depending on the owner flag. `ne` operator is not supported.
```suggestion
- `account.id`: Filter by the spender account ID or owner account ID, depending on the owner flag. `ne` operator is not supported. Only one occurrence allowed.
```

2024-01-18 18:10 UTC, steven-sheehy commented on HIP/hip-857.md
> +The default order for this API is currently ascending.
```suggestion
The default order for this API is ascending.
```

2024-01-18 18:10 UTC, steven-sheehy commented on HIP/hip-857.md
> +| token.id | eq | Y | Single occurrence only. Requires the presence of an `account.id` query parameter| ?token.id=lt:Y |
```suggestion
| token.id | eq | Y | Single occurrence only. Requires the presence of an `account.id` query parameter| ?account.id=X&token.id=eq:Y |
```

2024-01-18 18:10 UTC, steven-sheehy commented on HIP/hip-857.md
> +GET`api/v1/tokens/{tokenId}/listNfts`
```suggestion
GET `/api/v1/tokens/{tokenId}/nfts`
```

2024-01-18 18:10 UTC, steven-sheehy commented on HIP/hip-857.md
> +To retrieve NFT serial number level allowance information with a `tokenId`, you can use an existing API.
```suggestion
To retrieve NFT serial number level allowance information for a specific token ID you can use the existing API:
```

2024-01-19 18:33 UTC, steven-sheehy approved these changes
LGTM

2024-01-22 16:03 UTC, Ashe-Oro approved these changes
looks good! great feature and thank you both :)

2024-01-24 15:07 UTC, merged