Update HIP-17
hashgraph/hedera-improvement-proposal pull request #94
Opened 2021-05-25 13:12 UTC by failfmi

Update `HIP-17` regarding the latest feedback. 

* Update Token types
* Introduce `TokenSupplyType`
* Flatten of `TokenMintTransactionBody`, `TokenBurnTransactionBody`, `TokenWipeTransactionBody`.
* Flatten `TokenTransferList`
* Switch TokenMint `memo` -> `metadata`

2021-05-25 15:38 UTC, donaldthibeau approved these changes

2021-06-03 15:34 UTC, sergmetelin commented on HIP/hip-17.md
> +Describes a token that cannot be divided into smaller fractions. Meaning subdivision is not allowed - just whole number quantities. The current version of HTS supports these types of tokens. They can
decimals=0 should be `decimals=0`

2021-06-03 15:36 UTC, sergmetelin requested changes
Just a tiny formatting issue, but otherwise looks good!

2021-06-04 20:36 UTC, sergmetelin approved these changes

2021-06-07 00:40 UTC, merged