Automate HIP Management with Number Assignment and Status Updates
hashgraph/hedera-improvement-proposal pull request #962
Opened 2024-05-10 04:05 UTC by mgarbs

### Description:
This PR introduces two automated GitHub Actions workflows to streamline the management of HIPs (Hedera Improvement Proposals):

1. **Assign HIP Number and Rename File:**
    - This workflow identifies new HIP proposals by comparing the files modified in a pull request (PR) against the `main` branch.
    - If a new HIP is detected (a proposal that doesn't yet exist in the `main` branch), the workflow assigns a unique HIP number based on the PR number.
    - It renames the file following the standard format (`hip-<PR_NUMBER>.md`) and updates the `hip:` field in the document header with the assigned number.
    - Finally, it commits the changes back to the PR branch for a clear, consistent HIP file structure.

2. **Schedule Status Update Based on Last Call Time:**
    - This workflow automatically updates the status of HIPs that have reached their last call deadline.
    - It identifies merged PRs containing HIP files marked with a `status: Last Call` field.
    - The workflow calculates the appropriate delay until the specified `last-call-date-time`, and then applies the correct new status based on the HIP type and category.
    - It also adds or updates the `updated` field with the current date.
    - After making these adjustments, it creates a new PR for the changes and automatically merges it.

### Benefits:
- **Automation:** Streamlines HIP management, saving time and reducing manual errors.
- **Consistency:** Ensures all new and updated HIPs adhere to a consistent naming and status convention.
- **Transparency:** Offers clear communication through automatic PR messages and the precise updating of statuses and dates.

2024-05-10 14:08 UTC, sergmetelin approved these changes
LGTM

2024-05-10 15:54 UTC, rbarkerSL requested changes
Couple of comments

2024-05-10 15:54 UTC, rbarkerSL commented on .github/workflows/add-hip-number.yml
> +    runs-on: ubuntu-latest
should be on the self hosted runner

`runs-on: [self-hosted, Linux, medium, ephemeral`

2024-05-10 15:54 UTC, rbarkerSL commented on .github/workflows/add-hip-number.yml
> +      - name: Check out the code
Need to add a hardened runner step:

```
      - name: Harden Runner
        uses: step-security/harden-runner@a4aa98b93cab29d9b1101a6143fb8bce00e2eac4 # v2.7.1
        with:
          egress-policy: audit
 ```

2024-05-10 15:54 UTC, rbarkerSL commented on .github/workflows/add-hip-number.yml
> +        uses: actions/checkout@v2
`uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0`

2024-05-10 15:54 UTC, rbarkerSL commented on .github/workflows/add-hip-number.yml
> +
need to add defaults and permissions:

```
defaults:
    run:
        shell: bash
```
 
 ```
 permissions:
     contents: write
     issues: read
     pull-requests: write
     checks: write
```

2024-05-10 15:54 UTC, rbarkerSL commented on .github/workflows/schedule-last-call-date-end.yml
> +
need defaults:

```
defaults:
    runs:
        shell
```

2024-05-10 15:54 UTC, rbarkerSL commented on .github/workflows/schedule-last-call-date-end.yml
> +    runs-on: ubuntu-latest
Use the self-hosted runner:

`runs-on: [self-hosted, Linux, medium, ephemeral]`

2024-05-10 15:54 UTC, rbarkerSL commented on .github/workflows/schedule-last-call-date-end.yml
> +        uses: actions/checkout@v2
Actions should be using commit strings as versions:

`uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0`

2024-05-10 15:54 UTC, rbarkerSL commented on .github/workflows/schedule-last-call-date-end.yml
> +  contents: write
Add `packages: write` permisison

2024-05-20 22:20 UTC, mgarbs commented on .github/workflows/add-hip-number.yml
> +
Added

2024-05-20 22:20 UTC, mgarbs commented on .github/workflows/add-hip-number.yml
> +      - name: Check out the code
Added

2024-05-20 22:20 UTC, mgarbs commented on .github/workflows/schedule-last-call-date-end.yml
> +  contents: write
Added

2024-05-20 22:20 UTC, mgarbs commented on .github/workflows/schedule-last-call-date-end.yml
> +
Added

2024-05-21 01:17 UTC, rbarkerSL approved these changes

2024-05-21 19:07 UTC, merged